# Generated by Django 2.1.1 on 2018-10-19 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=75)),
                ('quantity', models.IntegerField(max_length=3)),
            ],
        ),
    ]
